name: VariablesDemo

on:
   workflow_dispatch:

env:
   DAY_OF_WEEK: Monday

Jobs:
  sample-job:
    runs-on: ubuntu_latest

    env:
       Greeting: Hello
       FirstName: Srinivas
    steps:
    -name: Print value of variable
    run: |
         echo “Value of Greeting is: ${{env.Greeting}}”
         echo “Value of Greeting is: $Greeting”
         echo “Value of Repo variable is: ${{vars.REPO_VARIABLE1}}”

    # name: "Hello, It’s Monday"
    If: ${{env.DAY_OF_WEEK}} == ‘Monday’
    -run: echo “${{env.Greeting}} ${{env.FirstName}}. Today is ${{env.DAY_OF_WEEK}}!”
        
