name: A sample workflow file
on: push
jobs:
  build-job:
    name: Demo website Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Check out code
    - name: Check out Code
      run: echo This is a Demo website!
    - name: Index content
      run: cat index.html
