name: A sample workflow file
on: push
jobs:
  build-job:
    name: Demo website Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/chekout@v1
      name: Checkout code
    - name: Checkout Code
      run: echo This is a Demo website!
    - name: Index content
      run: cat index.html
